// lecture13/office-hours-svelte/src/components/SlotCell.svelte
<script>
  import { fmtTime12 } from "../lib/utils.js";

  let { slot, onclick } = $props();
</script>

{#if slot.booking}
  <button type="button" class="slot booked" {onclick}>
    <span class="slot-name">{slot.booking.student_name}</span>
    <span class="slot-time">{fmtTime12(slot.start_time)}</span>
  </button>
{:else}
  <button type="button" class="slot available" {onclick}>
    <span class="slot-time">{fmtTime12(slot.start_time)}</span>
    <span style="font-size:0.65rem">Available</span>
  </button>
{/if}

// lecture13/office-hours-react/src/components/SlotCell.jsx
import { fmtTime12 } from "../utils.js";

export default function SlotCell({ slot, onClick }) {
  if (slot.booking) {
    return (
      <button type="button" className="slot booked" onClick={onClick}>
        <span className="slot-name">{slot.booking.student_name}</span>
        <span className="slot-time">{fmtTime12(slot.start_time)}</span>
      </button>
    );
  }

  return (
    <button type="button" className="slot available" onClick={onClick}>
      <span className="slot-time">{fmtTime12(slot.start_time)}</span>
      <span style={{ fontSize: "0.65rem" }}>Available</span>
    </button>
  );
}
