// lecture13/office-hours-react/src/components/Header.jsx
export default function Header({ onToggleSettings, onGoToToday }) {
  return (
    <header>
      <h1>Office Hours</h1>
      <div className="header-actions">
        <button className="btn btn-secondary" onClick={onToggleSettings}>
          Settings
        </button>
        <button className="btn btn-secondary" onClick={onGoToToday}>
          Today
        </button>
      </div>
    </header>
  );
}

// lecture13/office-hours-svelte/src/components/Header.svelte
<script>
  let { onToggleSettings, onGoToToday } = $props();
</script>

<header>
  <h1>Office Hours</h1>
  <div class="header-actions">
    <button class="btn btn-secondary" onclick={onToggleSettings}>Settings</button>
    <button class="btn btn-secondary" onclick={onGoToToday}>Today</button>
  </div>
</header>
